name: l i m z
permalink: /blog/:year/:month/:day/:title

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: limz
  email: "limz.li.10@gmail.com"
  facebook: yourname  
  github: limz10    
  twitter: yourname   
  reddit: yourname    
  linkedin: yourname  
  snapchat: yourname  
  instagram: yourname 
  youtube: yourlink   # eg. user/daattali or channel/daattali
  steam: yourname     
  twitch: yourname    

# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: false
  email: true
  twitter: true
  github: true
  reddit: false
  linkedin: false
  snapchat: false
  instagram: false
  youtube: false
  steam: false
  twitch: false

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "limz10.github.io"  # eg. "deanattali.com/beautiful-jekyll"
